name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

# Mutual exclusion for publishing to github pages
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Maven
        run: mvn -version
        shell: bash

      - name: Build
        run: mvn package
        shell: bash

      - name: Archive update site
        uses: actions/upload-pages-artifact@v1
        with:
          path: org.lflang.epoch.external.dependencies.repository/target/repository/

  publish:
    needs: build

    # Set permissions for github pages
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Publish P2 Repository
        id: deployment
        uses: actions/deploy-pages@v1